### ISSUE TITLE
个人的一些想法

### ISSUE THREAD

**Issue by amokiel** [zsakvo/wenku8x#1]
开发者你好！通过项目的截图可以了解到，这是一个很好看的轻小说文库第三方客户端。UI界面各方面都很不错。以后是否有可能开发本地阅读器呢，目前没有还没有找到美观的本地阅读器，尤其是Material You设计的本地阅读器。静读天下这类的我也用过，功能确实很强大，就是页面有点老旧。如果开发者有开发本地阅读器的想法，或者是有什么这种类型的本地阅读器项目，也可以推荐一下。冒昧打扰，挺喜欢这个项目的UI设计，还望开发者见谅，感激不尽！

**Comment by zsakvo** [comment]
本地阅读器的话，可以去 play store 看一下 阅微 这个应用哦。本 app 的 UI
灵感很大程度来自于此。其也是我们团队开发的，功能正在不断迭代，后续也正在准备上架国内商店。

amokiel ***@***.***> 于 2023年3月26日周日 08:06写道：

**Comment by zsakvo** [comment]
好的，谢谢。

amokiel ***@***.***> 于 2023年3月26日周日 12:45写道：
