### ISSUE TITLE
flutter run不了，那怕flutter create .成功之后也是

### ISSUE THREAD

**Issue by deepindo** [zsakvo/wenku8x#2]
package identifier or launch activity not found.
Please check /Users/xxxx/Downloads/wenku8x-master/android/app/src/main/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by anonymouszbs** [comment]
flutter pub get 
flutter pub run build_runner build --delete-conflicting-outputs

**Comment by zsakvo** [comment]
代码已更新
