### ISSUE TITLE
isar某些方法在新版本已经取消了

### ISSUE THREAD

**Issue by Fantuan-cell** [zsakvo/wenku8x#3]
Flutteer 3.13.5
isar最新版本isar: ^3.1.0+1
打开数据库方法已更改,可以修复下吗

**Comment by zsakvo** [comment]
嗯，目前正在着手修正一部分库的版本问题，并且在重写渲染部分。感谢关注 (⁠^⁠^⁠)

Coolcell ***@***.***> 于 2023年9月26日周二 16:20写道：

**Comment by zsakvo** [comment]
代码已更新

**Comment by zsakvo** [comment]
会支持，不过我需要考虑一下具体方案

Coolcell ***@***.***> 于 2023年10月11日周三 16:55写道：
